### ISSUE TITLE
Не отображается панель

### ISSUE THREAD

**Issue by prokopov-nikolai** [stfalcon-studio/ls-plugin_debugtoolbar#4]
<b>Не отображается панель. Сам Html код присутствует, но див #DebugToolbar почему-то display:none. Режим выставил 0. Кеш движка сбрасывал. Сайт http://makeit-up.ru</b>

Current version of LiveStreet: <b>0.4.2</b>

<b>Активные плагины</b>
aceAdminPanel, v.1.4.141 - Ok
RusUrls, v.0.5
Static page, v.1.2.1
Livestreet Profiler Plugin, v.1.0.1
AutoTown, v.0.0.1
Реферальная система, v.1.1
All tags, v.1.1
Мои Вещи, как на Лепре, v.0.2.0
Note, v.1.0
Must Have Blogs, v.1.0.0
Sitemap, v.0.2.1
BreadCumbs, v.0.1
Пингатор (исправленный), v.1.0.2
Main Meta, v.0.1.5
Robostat, v.0.5.3
SEO, v.0.2.0
LsPage, v.1.3
Birthdays, v.0.1
OpenID, v.1.4
Похожие записи, v.0.2
Каталог Pro, v.0.1
aceMySearch, v.1.4.106
Livestreet Wall, v.0.1
Контакты и социальные сервисы, v.1.0
ShowVotes, v.0.2
Debug Toolbar, v.0.1.0

**Comment by prokopov-nikolai** [comment]
все свои скрипты я пишу для сайта на jQuery, хотя в шаблоне подключен mootools.
Проблему совместимости решил для себя следующим образом.

<code>jQuery.noConflict();</code>
И потом везде пишу jQuery вместо доллара.

Было бы здорово если плагин был бы совместим и с версией 0.4

**Comment by fluxuator** [comment]
На данный момент плагин работает с 0.5.x версией движка и jQuery шаблонами
