### ISSUE TITLE
Не совместимость с LsGallery

### ISSUE THREAD

**Issue by verdet23** [stfalcon-studio/ls-plugin_debugtoolbar#5]
Не совместим с отметкой людей на фото в плагине LsGallery

**Comment by stfalcon** [comment]
больше инфы давай в отчетах о ошибках. в чем заключается несовместимость? какие ошибки в логе?

**Comment by verdet23** [comment]
В логах ошибки нету. Дебаг тулбар не дает перемещать поле отметки пользователя, видимо перехватывает евент.

**Comment by fluxuator** [comment]
Fixed
