### ISSUE TITLE
Совместимость с LS 1.0

### ISSUE THREAD

**Issue by stfalcon** [stfalcon-studio/ls-plugin_debugtoolbar#8]
> Закомментировал строку 89 в файле PluginDebugtoolbar.class.php и все заработало. Обнови. Думаю многим пригодится твой плагин:)

**Comment by fluxuator** [comment]
Исправлено.

**Comment by stfalcon** [comment]
Допишіть в рідмі інфу про новий функціонал. Треба ж гарно його презентувати :)

**Comment by fluxuator** [comment]
Fixed
